apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  rhtap/gitops: quarkus-arp23
  janus-idp.io/tekton: quarkus-arp23
  backstage.io/kubernetes-id: quarkus-arp23
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: quarkus-arp23
resources:
  - application-dev.yaml